# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
tolerations: []
affinity: {}

fullnameOverride: demo
replicaCount: 1
image:
  repository: demo
  tag: stable
  pullPolicy: IfNotPresent
imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

deployment:
  containerPort: 8080

probes:
  enabled: true
  liveness:
    path: /alive
    port: 8080
  readiness:
    path: /healthz
    port: 8080

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

# Example secrets for connection strings and credentials
secrets:
  mongodb:
    connectionString: "mongodb://user:password@mongo:27017/demo_webapi"
  redis:
    configuration: "localhost:6379"
  rabbitmq:
    username: "guest"
    password: "guest"
    hostnames: "rabbitmq"
    port: "5672"
  sqlserver:
    connectionString: "Server=sqlserver;Database=Genocs.BookStore.Demo;User Id=sa;Password=yourStrong(!)Password;"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
