###############################################################################
# Use this file inside Visual Studio code with 'REST Client' plugin 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###############################################################################

@url = https://localhost:5001


### Home / Welcome screen
GET {{url}}

### Health Check
GET {{url}}/healthz


### Send event with Masstransit
POST {{url}}/ServiceBusMassTransit/SubmitOrder
Content-Type: application/json

{

}


### Send event with Masstransit
POST {{url}}/ServiceBusMassTransit/OrderSubmitted
Content-Type: application/json

{

}

### Send command to Azure Service Bus Queue
POST {{url}}/ServiceBus/SendToQueueAzureServiceBusQueue
Content-Type: application/json

{

}

### Send event to Azure Service Bus Topic
POST {{url}}/ServiceBus/SendToTopicAzureServiceBusTopic
Content-Type: application/json

{

  "fullname": "John Doe",
  "address": "New York City, Street XYZ"
}