services:
  rabbitmq:
    image: masstransit/rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    networks:
      - genocs
    # network_mode: host
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia

  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - genocs
    # network_mode: host
    volumes:
      - mongodb:/data/db

networks:
  genocs:
    name: genocs-network
    driver: bridge

volumes:
  mongodb:
    driver: local
  rabbitmq:
    driver: local
