<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Genocs.Library.Demo.Infrastructure</RootNamespace>
        <AssemblyName>Genocs.Library.Demo.Infrastructure</AssemblyName>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
    </ItemGroup>

</Project>
