<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Genocs.Identities.WebApi</RootNamespace>
        <AssemblyName>Genocs.Identities.WebApi</AssemblyName>
        <IsPackable>false</IsPackable>
        <UserSecretsId>Genocs</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
        <!-- Disable web.config transformation for Docker builds -->
        <TransformWebConfigEnabled>false</TransformWebConfigEnabled>
        <WebConfigTransformEnabled>false</WebConfigTransformEnabled>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Genocs.ServiceDiscovery.Consul\Genocs.ServiceDiscovery.Consul.csproj" />
        <ProjectReference Include="..\..\..\Genocs.Logging\Genocs.Logging.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="certs\**" CopyToPublishDirectory="Always" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="logs\" />
    </ItemGroup>

</Project>
