###############################################################################
# Use this file inside Visual Studio code with 'REST Client' plugin 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###############################################################################

#@url = https://localhost:5001
#@apigateway = http://localhost:5000
#@identity = https://localhost:5271

# Container version
@apigateway = http://localhost:5500
@identity = http://localhost:5510



### Sign up as Admin
POST {{identity}}/sign-up
Content-Type: application/json

{
  "Email": "giovanni.nocco@gmail.com",
  "Name": "Giovanni",
  "Password": "Pas3word123!",
  "Role": "Admin",
  "Permissions": null
}

### Sign in
POST {{identity}}/sign-in
Content-Type: application/json

{
  "Name": "Giovanni",
  "Password": "Pas3word123!"
}


### Get list of users
GET {{identity}}/users?page=1


### Revoke the refresh token
POST {{identity}}/refresh-tokens/revoke

{
  "RefreshToken" : "9m1vfuKUfY2DSIZYitmywy7dAVVTfMJLFeH34l6"
}


### Get list of products using the API Gateway
GET {{apigateway}}/products-service/products/ec5983de-c667-4ad3-8e0e-d42e653572b9


### Create new product using the API Gateway
POST {{apigateway}}/products-service/products

{
  "unitPrice" : 50.12,
  "sku": "ABC_123"
}


### Create a new order using the API Gateway
POST {{apigateway}}/orders-service/orders
Content-Type: application/json

{
  "CustomerId": "ec5983de-c667-4ad3-8e0e-d42e653572b9",
  "productId" : "3be72f8e-0219-4ffc-b10d-2b29e8bd54b6"
}