<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <PackageId>Genocs.Saga.Integrations.MongoDB</PackageId>
        <AssemblyName>Genocs.Saga.Integrations.MongoDB</AssemblyName>
        <PackageId>Genocs.Saga.Integrations.MongoDB</PackageId>
        <Title>Genocs MongoDB saga integration</Title>
        <Description>MongoDB storage integration for Genocs saga state management.</Description>
        <PackageTags>genocs saga mongodb state-management orchestration</PackageTags>
    </PropertyGroup>


    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <ProjectReference Include="..\Genocs.Core\Genocs.Core.csproj" />
        <ProjectReference Include="..\Genocs.Persistence.MongoDB\Genocs.Persistence.MongoDB.csproj" />
        <ProjectReference Include="..\Genocs.Saga\Genocs.Saga.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <PackageReference Include="Genocs.Core" Version="9.0.0-beta007" />
        <PackageReference Include="Genocs.Persistence.MongoDB" Version="9.0.0-beta007" />
        <PackageReference Include="Genocs.Saga" Version="9.0.0-beta007" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
