apiVersion: v1
kind: Pod

metadata:
  name: apigateway-deployment
  labels:
    run: apigateway

spec:
  containers:
    - name: apigateway
      image: genocs/apigateway:1.0.0
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: RABBITMQ_HOST_NAME
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: RABBITMQ_HOST_NAME
        - name: RABBITMQ_USER_NAME
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: RABBITMQ_USER_NAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: RABBITMQ_PASSWORD
      resources:
        requests:
          cpu: "200m" #20% of a core
          memory: "20Mi"
        limits:
          cpu: "500m" #50% of a core
          memory: "50Mi"
  restartPolicy: Always
