apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apps.fullname" . }}-apigateway
  labels:
    app: apigateway
    chart: {{ include "apps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apigateway
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: apigateway
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: apigateway
          image: "{{ .Values.apigateway.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.apigateway.service.port }}
              name: http
              protocol: TCP
          env:
            {{- include "apps.commonEnv" (dict "root" . "consulAddress" .Values.apigateway.consulAddress) | nindent 12 }}
            - name: reverseProxy__clusters__identities-cluster__destinations__destination1__address
              value: {{ .Values.apigateway.reverseProxy.clusters.identities | quote }}
            - name: reverseProxy__clusters__products-cluster__destinations__destination1__address
              value: {{ .Values.apigateway.reverseProxy.clusters.products | quote }}
            - name: reverseProxy__clusters__orders-cluster__destinations__destination1__address
              value: {{ .Values.apigateway.reverseProxy.clusters.orders | quote }}
            - name: reverseProxy__clusters__notifications-cluster__destinations__destination1__address
              value: {{ .Values.apigateway.reverseProxy.clusters.notifications | quote }}
          {{- include "apps.probes" .Values.apigateway | nindent 10 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
