apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apps.fullname" . }}-notifications
  labels:
    app: notifications
    chart: {{ include "apps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notifications
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: notifications
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: notifications
          image: "{{ .Values.notifications.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.notifications.service.port }}
              name: http
              protocol: TCP
          env:
            # Example: inject secrets as env vars if needed
          resources:
            {}
      imagePullSecrets:
        []
