apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  labels:
    app: notifications
    chart: {{ include "apps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.notifications.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: notifications
    release: {{ .Release.Name }}
