apiVersion: v1
kind: Service
metadata:
  name: {{ include "apps.fullname" . }}-orders
  labels:
    app: orders
    chart: {{ include "apps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.orders.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: orders
    release: {{ .Release.Name }}
