apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "demo.fullname" . }}
  labels:
    app: {{ template "demo.name" . }}
    chart: {{ template "demo.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "demo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "demo.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
            - name: ConnectionStrings__BookStore
              valueFrom:
                secretKeyRef:
                  name: {{ template "demo.fullname" . }}-sqlserver
                  key: connectionString
            - name: mongodb__connectionString
              valueFrom:
                secretKeyRef:
                  name: {{ template "demo.fullname" . }}-mongodb
                  key: connectionString
            - name: redis__configuration
              valueFrom:
                secretKeyRef:
                  name: {{ template "demo.fullname" . }}-redis
                  key: configuration
            - name: rabbitmq__username
              valueFrom:
                secretKeyRef:
                  name: {{ template "demo.fullname" . }}-rabbitmq
                  key: username
            - name: rabbitmq__password
              valueFrom:
                secretKeyRef:
                  name: {{ template "demo.fullname" . }}-rabbitmq
                  key: password
            - name: rabbitmq__hostnames
              valueFrom:
                secretKeyRef:
                  name: {{ template "demo.fullname" . }}-rabbitmq
                  key: hostnames
            - name: rabbitmq__port
              valueFrom:
                secretKeyRef:
                  name: {{ template "demo.fullname" . }}-rabbitmq
                  key: port
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
