using Genocs.Common.CQRS.Events;

namespace Genocs.Common.Domain.Entities;

/// <summary>
/// Apply this marker interface only to aggregate root entities
/// Repositories will only work with aggregate roots, not their children.
/// </summary>
public interface IAggregateRoot : IEntity;

public interface IAggregateRoot<TKey> : IEntity<TKey>, IAggregateRoot, IGeneratesDomainEvents;

/// <summary>
/// This interface is used to identify a domain event source.
/// </summary>
public interface IGeneratesDomainEvents
{
    /// <summary>
    /// The domain events that have been generated by this aggregate root.
    /// This is used to track changes and publish events after the aggregate root has been persisted.
    /// </summary>
    List<IEvent>? DomainEvents { get; }
}
