<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Genocs.Library.Demo.ServiceBus.Worker</RootNamespace>
        <AssemblyName>Genocs.Library.Demo.ServiceBus.Worker</AssemblyName>
        <IsPackable>false</IsPackable>
        <UserSecretsId>Genocs</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
        <TransformWebConfigEnabled>false</TransformWebConfigEnabled>
        <WebConfigTransformEnabled>false</WebConfigTransformEnabled>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Genocs.Logging\Genocs.Logging.csproj" />
        <ProjectReference Include="..\..\..\Genocs.Messaging.RabbitMQ\Genocs.Messaging.RabbitMQ.csproj" />
        <ProjectReference Include="..\..\..\Genocs.Persistence.MongoDB\Genocs.Persistence.MongoDB.csproj" />
        <ProjectReference Include="..\..\..\Genocs.Telemetry\Genocs.Telemetry.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Contracts\Contracts.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
</Project>
