<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <PackageId>Genocs.Saga.Integrations.Redis</PackageId>
        <AssemblyName>Genocs.Saga.Integrations.Redis</AssemblyName>
        <PackageId>Genocs.Saga.Integrations.Redis</PackageId>
        <Title>Genocs Redis saga integration</Title>
        <Description>Redis storage integration for Genocs saga state management.</Description>
        <PackageTags>genocs saga redis state-management orchestration</PackageTags>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <ProjectReference Include="..\Genocs.Core\Genocs.Core.csproj" />
        <ProjectReference Include="..\Genocs.Saga\Genocs.Saga.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <PackageReference Include="Genocs.Core" Version="9.0.0-beta002" />
        <PackageReference Include="Genocs.Saga" Version="9.0.0-beta002" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="StackExchange.Redis" Version="2.12.8" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Genocs.Saga.UnitTests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
