@Genocs.Core.Demo.HelloWorld_HostAddress = https://localhost:5070
@bookStoreBaseUrl = {{Genocs.Core.Demo.HelloWorld_HostAddress}}/api/bookstore
@authorId = 00000000-0000-0000-0000-000000000000
@bookId = 00000000-0000-0000-0000-000000000000

# BookStore - list authors
GET {{bookStoreBaseUrl}}/authors
Accept: application/json

###

# BookStore - create author
POST {{bookStoreBaseUrl}}/authors
Content-Type: application/json

{
	"firstName": "Brandon",
	"lastName": "Sanderson",
	"biography": "Fantasy and science fiction author."
}

###

# BookStore - get author by id
GET {{bookStoreBaseUrl}}/authors/{{authorId}}
Accept: application/json

###

# BookStore - list books
GET {{bookStoreBaseUrl}}/books
Accept: application/json

###

# BookStore - create book
POST {{bookStoreBaseUrl}}/books
Content-Type: application/json

{
	"title": "The Way of Kings",
	"isbn": "978-0765365279",
	"price": 13.99,
	"publishedOnUtc": "2010-08-31T00:00:00Z",
	"authorIds": [
		"{{authorId}}"
	]
}

###

# BookStore - get book by id
GET {{bookStoreBaseUrl}}/books/{{bookId}}
Accept: application/json

###

# BookStore - update book
PUT {{bookStoreBaseUrl}}/books/{{bookId}}
Content-Type: application/json

{
	"title": "The Way of Kings (Updated)",
	"isbn": "978-0765365279",
	"price": 15.49,
	"publishedOnUtc": "2010-08-31T00:00:00Z",
	"authorIds": [
		"{{authorId}}"
	]
}

###

# BookStore - delete book
DELETE {{bookStoreBaseUrl}}/books/{{bookId}}

###
