<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Genocs.Identities.Application</RootNamespace>
        <AssemblyName>Genocs.Identities.Application</AssemblyName>
        <IsPackable>false</IsPackable>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Genocs.Auth" Version="9.0.0" />
        <PackageReference Include="Genocs.Logging" Version="9.0.0" />
        <PackageReference Include="Genocs.Telemetry" Version="9.0.0" />
        <PackageReference Include="Genocs.LoadBalancing.Fabio" Version="9.0.0" />
        <PackageReference Include="Genocs.Persistence.Redis" Version="9.0.0" />
        <PackageReference Include="Genocs.Http" Version="9.0.0" />
        <PackageReference Include="Genocs.Messaging.Outbox.MongoDB" Version="9.0.0" />
        <PackageReference Include="Genocs.Messaging.RabbitMQ" Version="9.0.0" />
        <PackageReference Include="Genocs.Persistence.MongoDB" Version="9.0.0" />
        <PackageReference Include="Genocs.Secrets.HashicorpKeyVault" Version="9.0.0" />
        <PackageReference Include="Genocs.WebApi.CQRS" Version="9.0.0" />
        <PackageReference Include="Genocs.WebApi.OpenApi" Version="9.0.0" />
    </ItemGroup>

</Project>
